// 提唱者マスタ（用語DB・新）— network/data/terms.json に対応する手書きの割当表
// 原綴り・刊行年はDBの提唱者欄に書かれたものだけを使う。書かれていないものは null にして注記を残す。
// 用語はNotionの「名前」で引く。build_master.js が terms.json と突き合わせてページIDに変換する。
// 語を足したとき: T に1行足して `node build_master.js` を実行する（未登録でもページ側は文字列照合で仮表示する）。
// role: 提唱＝提唱者・原典 / 代表＝代表的論者・代表的定義 / 関連＝関連論者・参照・背景 / 整理＝本書の章著者による整理
// src: 序章（西谷真規子）／第1章（山田哲也）

// 人物: id: [表示名, 原綴り, 別名[], 年（DB本文に記載）, 年の注記]
const P = {
  // 共通id（旧マスタと同じ）
  keohane:   ["ロバート・コヘイン", "Robert O. Keohane", ["Keohane"], 1977],
  nye:       ["ジョセフ・ナイ", "Joseph S. Nye", ["Nye"], 1977, "ソフト・パワーの初出年はDBが断定していない（序章はNye 2005を参照）"],
  krasner:   ["スティーヴン・クラズナー", "Stephen D. Krasner", ["Krasner"], 1982],
  ruggie:    ["ジョン・ラギー", "John G. Ruggie", ["Ruggie"], 2011, "指導原則の人権理事会支持年。グローバル・コンパクト関与の年はDBに記載なし"],
  abbott:    ["アボット", "Kenneth W. Abbott", ["Abbott"], 2009],
  snidal:    ["スナイダル", "Duncan Snidal", ["Snidal"], 2009],
  genschel:  ["ゲンシェル", "Philipp Genschel", [], 2015],
  zangl:     ["ツァングル", "Bernhard Zangl", [], 2015],
  hawkins:   ["ホーキンス", "Darren G. Hawkins", [], 2006],
  lake:      ["レイク", "David A. Lake", [], 2006],
  nielson:   ["ニールソン", "Daniel L. Nielson", [], 2006],
  tierney:   ["ティアニー", "Michael J. Tierney", [], 2006],
  rosenau:   ["ローズノー", "James N. Rosenau", ["Rosenau"], 1992],
  czempiel:  ["チェンピール", "Ernst-Otto Czempiel", ["Czempiel"], 1992],
  mitrany:   ["ミトラニー", "David Mitrany", ["Mitrany"], 1943],
  march:     ["マーチ", "James G. March", [], null, "DBに刊行年の記載なし"],
  olsen:     ["オルセン", "Johan P. Olsen", [], null, "DBに刊行年の記載なし"],
  alter:     ["アルター", "Karen J. Alter", [], 2009],
  meunier:   ["ムニエ", "Sophie Meunier", [], 2009],
  ostrom:    ["エリノア・オストロム", "Elinor Ostrom", ["Ostrom"], 2010],
  risse:     ["リッセ", "Thomas Risse", ["Risse"], 2000],
  barnett:   ["バーネット", "Michael Barnett", ["Barnett"], 1999],
  finnemore: ["フィネモア", "Martha Finnemore", ["Finnemore"], 1999],
  phaas:     ["ピーター・ハース", "Peter M. Haas", ["Haas"], 1990, "序章はHaas（1990）、補足原典は1992"],
  wallerstein:["ウォーラーステイン", "Immanuel Wallerstein", ["Wallerstein"], null, "DBは初出年を未確認として記載していない"],
  williamson:["ジョン・ウィリアムソン", "John Williamson", ["Williamson"], 1989, "会議は1989年、刊行は1990年"],
  // 新DBのみ
  weiss:     ["トマス・ワイス", "Thomas G. Weiss", ["Weiss"], 2009],
  carayannis:["カラヤニス", "Tatiana Carayannis", [], 2009],
  jolly:     ["ジョリー", "Richard Jolly", [], 2009],
  forsythe:  ["フォーサイス", "David P. Forsythe", ["Forsythe"], 2017, "原綴りのフルネームはDBに記載なし（姓のみ）"],
  coate:     ["コート", "Roger A. Coate", ["Coate"], 2017, "原綴りのフルネームはDBに記載なし（姓のみ）"],
  pease:     ["ピーズ", "Kelly-Kate Pease", ["Pease"], 2017, "原綴りのフルネームはDBに記載なし（姓のみ）"],
  matsumoto: ["松本悟", "", [], 2013],
  oshiba:    ["大芝亮", "", [], 2013],
  scharpf:   ["シャルプフ", "Fritz W. Scharpf", ["Scharpf"], 1999],
  schmidt:   ["シュミット", "Vivien A. Schmidt", ["Schmidt"], 2013],
  zurn:      ["ツュルン", "Michael Zürn", ["Zürn", "Zurn"], 2013, "序章参照は2013、著書は2018"],
  endo:      ["遠藤乾", "", [], 2010],
  uemura:    ["上村雄彦", "", [], 2021],
  sassen:    ["サッセン", "Saskia Sassen", ["Sassen"], 2003],
  young:     ["オラン・ヤング", "Oran R. Young", ["Young"], 1996],
  murphy:    ["マーフィー", "Murphy", ["Murphy"], 2015, "原綴りのフルネームはDBに記載なし"],
  navari:    ["コーネリア・ナヴァリ", "Cornelia Navari", ["ナヴァリ"], 2002],
  kaldor:    ["メアリー・カルドー", "Mary Kaldor", ["Kaldor"], null, "DBは原典の版・刊行年を未照合としている"],
  hayek:     ["ハイエク", "Friedrich Hayek", [], null, "DBに刊行年の記載なし"],
  friedman:  ["フリードマン", "Milton Friedman", [], null, "DBに刊行年の記載なし"],
  lukes:     ["ルークス", "Steven Lukes", ["Lukes"], 2005, "序章参照年。DBは原典全文を未照合としている"],
  krisch:    ["クリッシュ", "Nico Krisch", ["Krisch"], 2017, "序章参照年。DBは原典全文を未照合としている"],
  yamada:    ["山田哲也", "", [], 2021],
  nishitani: ["西谷真規子", "", [], 2021],
  annan:     ["コフィ・アナン", "Kofi Annan", ["Annan"], 1999],
  duvall:    ["デュヴァル", "Raymond Duvall", ["Duvall"], 2005],
  manners:   ["マナーズ", "Ian Manners", ["Manners"], 2002, "序章参照年。DBは原典全文を未照合としている"],
  habermas:  ["ハーバーマス", "Jürgen Habermas", ["Habermas"], null, "DBに刊行年の記載なし"],
  slaughter: ["スローター", "Anne-Marie Slaughter", ["Slaughter"], 2004],
  roosevelt: ["エレノア・ルーズベルト", "Eleanor Roosevelt", [], 1948],
  nakanishi: ["中西寛", "", [], 2003],
  cox:       ["ロバート・コックス", "Robert W. Cox", ["Cox"], 1986, "序章参照年。DBは原典全文を未照合としている"],
  gramsci:   ["グラムシ", "Antonio Gramsci", ["Gramsci"], null, "DBに刊行年の記載なし"],
};

// 機関・文書
const I = {
  un:           ["国連（システム全体・取り組み）", "機関", "国連"],
  un_ga:        ["国連総会（決議・採択文書）", "機関", "国連"],
  un_hrc:       ["国連人権理事会（旧人権委員会・特別手続）", "機関", "国連"],
  un_sg:        ["国連事務総長告示（ST/SGB）", "文書", "国連"],
  un_charter:   ["国連憲章（1945）", "文書", "国連"],
  league_cov:   ["国際連盟規約（1919）", "条約", "条約・国際法"],
  bretton_woods:["ブレトン・ウッズ協定（1944）", "条約", "貿易・通貨レジーム"],
  wb_board:     ["世界銀行理事会（決議 IBRD 93-10 / IDA 93-6）", "機関", "貿易・通貨レジーム"],
  world_bank:   ["世界銀行（構造調整貸付）", "機関", "貿易・通貨レジーム"],
  cgg:          ["グローバル・ガバナンス委員会『地球リーダーシップ』（1995）", "文書", "国際委員会"],
};

// 用語（名前キー）: p は [id, role] の配列（文字列だけなら role=提唱）
const T = {
  "NGO・市民社会": { p: [["weiss","関連"],["carayannis","関連"],["jolly","関連"],["matsumoto","関連"],["oshiba","関連"]], none: true, src: ["序章","第1章"] },
  "UNESCO脱退問題（米英の脱退・復帰）": { p: [["yamada","整理"]], none: true, src: ["第1章"], note: "歴史的事件" },
  "アナーキー（無政府状態）": { p: [], none: true, src: ["序章"] },
  "インフォーマル・ガバナンス": { p: [], none: true, src: ["序章"] },
  "インプット正統性・スループット正統性・アウトプット正統性": { p: ["scharpf","schmidt"], src: ["第1章"], note: "インプット／アウトプット＝Scharpf（1999）、スループット＝Schmidt（2013）" },
  "ウェストファリア体制": { p: [], none: true, src: ["序章"] },
  "オーケストレーション・間接的ガバナンス": { p: ["abbott","genschel","snidal","zangl"], src: ["序章"] },
  "ガバナンスの三角形": { p: ["abbott","snidal"], src: ["序章"] },
  "ガバナンスの正統性・民主的統制": { p: [["zurn","関連"],["scharpf","関連"],["schmidt","関連"],["yamada","整理"]], none: true, src: ["序章","第1章"] },
  "ガバナンス・モード": { p: [], none: true, src: ["序章"] },
  "グローバル・ガバナンス": { p: ["rosenau","czempiel",["cgg","機関"],["endo","関連"],["yamada","整理"]], src: ["序章","第1章"] },
  "グローバル・タックス": { p: [["uemura","関連"]], none: true, src: ["序章"], note: "第18章の著者は上村雄彦" },
  "グローバル公共財": { p: [], none: true, src: ["序章"] },
  "グローバル化（グローバリゼーション）": { p: [["sassen","関連"]], none: true, src: ["序章"] },
  "ソフト・ローとハード・ロー": { p: [], none: true, src: ["序章"] },
  "トランスナショナル・レジーム": { p: [], none: true, src: ["序章"] },
  "ビジネスと人権に関する指導原則": { p: ["ruggie",["un_hrc","機関"]], src: ["序章"] },
  "プライベート・スタンダード": { p: [["abbott","関連"],["snidal","関連"]], none: true, src: ["序章"] },
  "プライベート・レジーム": { p: [["abbott","関連"],["snidal","関連"]], none: true, src: ["序章"] },
  "ミレニアム開発目標（MDGs）": { p: [["un","機関"]], src: ["序章"] },
  "レジーム・コンプレックス（レジーム複合体）": { p: [["alter","代表"],["meunier","代表"],["young","関連"]], src: ["序章"] },
  "ワシントン・コンセンサス": { p: ["williamson",["yamada","整理"]], src: ["第1章"] },
  "世界銀行インスペクション・パネル": { p: [["wb_board","機関"],["yamada","整理"]], src: ["第1章"] },
  "主権コスト": { p: [], none: true, src: ["序章"] },
  "企業の社会的責任（CSR）": { p: [], none: true, src: ["序章"] },
  "公共政策ネットワーク・官民パートナーシップ": { p: [["ruggie","関連"],["abbott","関連"],["snidal","関連"]], none: true, src: ["序章"] },
  "協調的安全保障・ヨーロッパ協調": { p: [["murphy","関連"]], none: true, src: ["序章"] },
  "国家主権・主権平等・内政不干渉": { p: [], none: true, src: ["序章"] },
  "国連の「3つの顔」（第1・第2・第3の国連）": { p: ["weiss","carayannis","jolly",["forsythe","関連"],["coate","関連"],["pease","関連"],["yamada","整理"]], src: ["第1章"] },
  "国連の下部機関・専門機関（UNHCR・UNDP・IMF・世界銀行）": { p: [["un_ga","機関"],["bretton_woods","機関"],["yamada","整理"]], src: ["第1章"] },
  "国連グローバル・コンパクト": { p: [["un","機関"],["ruggie","関連"]], src: ["序章"], note: "Ruggieは関与者（単独の創設者ではない）" },
  "国際レジーム": { p: [["krasner","代表"]], src: ["序章"] },
  "国際機構の偏向（バイアス）とその是正": { p: [["yamada","整理"],["zurn","関連"],["barnett","関連"],["finnemore","関連"]], src: ["第1章"] },
  "国際機構の正統性（合法性との区別・3段階）": { p: [["yamada","整理"]], none: true, src: ["第1章"] },
  "国際機構・地域機構": { p: [["yamada","整理"],["weiss","関連"]], none: true, src: ["序章","第1章"] },
  "国際機構論とグローバル・ガバナンス論の関係": { p: [["yamada","提唱"]], src: ["第1章"], note: "山田哲也の章そのものの議論" },
  "国際秩序・世界秩序": { p: [], none: true, src: ["序章"] },
  "国際行政連合": { p: [["yamada","整理"]], none: true, src: ["第1章"], note: "歴史的制度" },
  "国際関係の法化": { p: [], none: true, src: ["序章"] },
  "地域主義・ナショナリズム・ポピュリズム": { p: [["yamada","整理"]], none: true, src: ["序章","第1章"] },
  "地域貿易協定（RTA）": { p: [], none: true, src: ["序章"] },
  "多中心的ガバナンス": { p: [["ostrom","代表"]], src: ["序章"] },
  "多主体性": { p: [["nishitani","整理"],["abbott","関連"],["snidal","関連"]], src: ["序章"] },
  "多争点性・問題領域の複合化": { p: [["nishitani","整理"],["keohane","関連"],["nye","関連"]], src: ["序章"] },
  "多国籍企業": { p: [], none: true, src: ["序章"] },
  "多層的ガバナンス（マルチレベル・ガバナンス）": { p: [["zurn","関連"]], none: true, src: ["序章"] },
  "持続可能な開発目標（SDGs）": { p: [["un_ga","機関"]], src: ["序章"] },
  "政府なき統治（governance without government）": { p: ["rosenau","czempiel",["navari","関連"],["yamada","整理"]], src: ["序章","第1章"] },
  "新しい戦争・紛争の複合化": { p: [["kaldor","代表"]], src: ["序章"] },
  "新しい社会運動": { p: [], none: true, src: ["序章"] },
  "新自由主義（経済政策）": { p: [["hayek","関連"],["friedman","関連"],["williamson","関連"],["yamada","整理"]], none: true, src: ["序章","第1章"], note: "思想的源流＝Hayek・Friedman、政策パッケージ＝Williamson" },
  "構造調整貸付・政策コンディショナリティ": { p: [["world_bank","機関"],["matsumoto","関連"],["oshiba","関連"],["yamada","整理"]], src: ["序章","第1章"] },
  "権力の三次元・アジェンダ設定": { p: ["lukes"], src: ["序章"] },
  "権威の流動化（liquid authority）": { p: ["krisch"], src: ["序章"] },
  "権威・グローバル・ガバナー": { p: [], none: true, src: ["序章"] },
  "気候変動の緩和・適応・気候工学": { p: [], none: true, src: ["序章"] },
  "特別報告者（国連人権理事会の特別手続）とOHCHR": { p: [["un_hrc","機関"],["un_ga","機関"],["yamada","整理"]], src: ["第1章"] },
  "結果の論理（logic of consequences）": { p: [["risse","関連"]], none: true, src: ["序章"], note: "比較整理の原典はRisse（2000）" },
  "脱国家化（denationalization）": { p: ["sassen"], src: ["序章"] },
  "規範遵守（compliance）と実効性": { p: [], none: true, src: ["序章"] },
  "超国家的ガバナンス": { p: [], none: true, src: ["序章"] },
  "遵守・調整・正統性のトリレンマ": { p: [["nishitani","提唱"]], src: ["序章"], note: "西谷真規子の序章の整理そのもの" },
  "非国家主体": { p: [], none: true, src: ["序章"] },
  "コンストラクティビズム（構成主義）": { p: [["ruggie","関連"],["risse","関連"],["barnett","関連"],["duvall","関連"]], none: true, src: ["序章"] },
  "事務総長告示（ST/SGB）の外部効果・グッド・プラクティスによる規範化": { p: [["yamada","整理"],["annan","関連"],["un_sg","機関"]], src: ["第1章"] },
  "国際事務局（国際官僚機構）の自律性": { p: [["barnett","代表"],["finnemore","代表"],["yamada","整理"]], src: ["第1章"] },
  "国際機構を通じた規範形成（伝統的理解とGG論の問題提起）": { p: [["yamada","整理"],["matsumoto","関連"],["oshiba","関連"]], src: ["第1章"] },
  "生産的権力と権力の四分類": { p: ["barnett","duvall"], src: ["序章"] },
  "知識の権力": { p: [["phaas","代表"]], src: ["序章"] },
  "知識共同体（認識共同体／epistemic community）": { p: [["phaas","代表"]], src: ["序章"] },
  "規範的パワー": { p: [["manners","代表"]], src: ["序章"] },
  "討議の論理（logic of arguing）": { p: ["risse",["habermas","関連"]], src: ["序章"] },
  "適切さの論理（logic of appropriateness）": { p: ["march","olsen",["risse","関連"]], src: ["序章"] },
  "リアリズム": { p: [], none: true, src: ["序章"] },
  "勢力均衡・多極性": { p: [], none: true, src: ["序章"] },
  "覇権・一極構造": { p: [], none: true, src: ["序章"] },
  "ソフト・パワー": { p: ["nye"], src: ["序章"] },
  "トランスガバメンタル・ネットワーク": { p: [["slaughter","代表"]], src: ["序章"] },
  "ネオリベラル制度論": { p: [["keohane","代表"]], src: ["序章"] },
  "世界人権宣言と「宣言→条約」型の国際人権規範形成": { p: [["un_ga","機関"],["roosevelt","関連"],["yamada","整理"]], src: ["第1章"] },
  "国家機能の「退化」と「進化」（国際組織化）": { p: ["navari",["yamada","整理"]], src: ["第1章"] },
  "国際共同体（中西寛）": { p: ["nakanishi",["yamada","整理"]], src: ["第1章"] },
  "多孔的国家・国家の細分化": { p: [["slaughter","関連"],["nishitani","整理"]], src: ["序章"], note: "「多孔的国家」は序章での説明表現" },
  "本人・代理人（プリンシパル・エージェント）関係": { p: [["hawkins","代表"],["lake","代表"],["nielson","代表"],["tierney","代表"],["yamada","整理"]], src: ["第1章"], note: "起源は経済学のエージェンシー理論" },
  "機能主義（functionalism）": { p: ["mitrany",["navari","関連"],["yamada","整理"]], src: ["第1章"] },
  "複合的相互依存": { p: ["keohane","nye"], src: ["序章"] },
  "集団安全保障（国際連盟・国連）": { p: [["league_cov","機関"],["un_charter","機関"],["yamada","整理"]], src: ["第1章"] },
  "ネオグラムシアン（新グラムシ主義）": { p: [["cox","代表"],["gramsci","関連"]], src: ["序章"] },
  "世界システム論": { p: ["wallerstein"], src: ["序章"] },
  "批判理論と問題解決理論": { p: [["cox","関連"]], src: ["序章"], note: "区別の関連論者としてCox（1986）" },
};

module.exports = { P, I, T };
