// master_src.js への追加分（2026-09-09）。build_master.js が読み込んでマージする。
// 人物: id: [表示名, 原綴り, 別名[], 年, 注記]
const P = {
  waltz:        ["ケネス・ウォルツ", "Kenneth N. Waltz", ["ウォルツ"], 1979],
  morgenthau:   ["モーゲンソー", "Hans J. Morgenthau", [], 1948],
  herz:         ["ジョン・ハーツ", "John H. Herz", ["ハーツ"], 1950],
  jervis:       ["ロバート・ジャーヴィス", "Robert Jervis", ["ジャーヴィス"], 1976],
  walt:         ["スティーヴン・ウォルト", "Stephen M. Walt", ["ウォルト"], 1987],
  schweller:    ["シュウェラー", "Randall L. Schweller", [], 1994],
  kindleberger: ["キンドルバーガー", "Charles P. Kindleberger", [], 1973],
  gilpin:       ["ギルピン", "Robert Gilpin", [], 1975],
  organski:     ["オルガンスキー", "A. F. K. Organski", [], 1958],
  kondratiev:   ["コンドラチェフ", "Nikolai Kondratiev", [], null, "1920年代とのみ記載"],
  modelski:     ["モデルスキー", "George Modelski", [], 1987],
  rose:         ["ギデオン・ローズ", "Gideon Rose", [], 1998],
  merton:       ["ロバート・マートン", "Robert K. Merton", [], null, "刊行年の記載なし"],
  ikenberry:    ["アイケンベリー", "G. John Ikenberry", [], 2011],
  popper:       ["カール・ポパー", "Karl Popper", [], null, "刊行年の記載なし"],
  kant:         ["カント", "Immanuel Kant", [], 1795],
  carr:         ["E.H.カー", "Edward Hallett Carr", ["カー"], 1939],
  farrell:      ["ファレル", "Henry Farrell", [], 2019],
  newman:       ["ニューマン", "Abraham L. Newman", [], 2019],
  grieco:       ["グリーコ", "Joseph M. Grieco", [], 1988],
  deutsch:      ["カール・ドイッチュ", "Karl W. Deutsch", ["ドイッチュ"], 1957],
  doyle:        ["マイケル・ドイル", "Michael W. Doyle", ["ドイル"], 1983],
  dbaldwin:     ["デイヴィッド・ボールドウィン", "David A. Baldwin", [], 1993],
  allison:      ["グレアム・アリソン", "Graham T. Allison", ["アリソン"], 1971],
  lindblom:     ["リンドブロム", "Charles E. Lindblom", [], 1959],
  simon:        ["ハーバート・サイモン", "Herbert A. Simon", ["サイモン"], 1947],
  wohlstetter:  ["ロバータ・ウォルステッター", "Roberta Wohlstetter", [], 1962],
  janis:        ["アーヴィング・ジャニス", "Irving L. Janis", ["ジャニス"], 1972],
  kahneman:     ["カーネマン", "Daniel Kahneman", [], 1979],
  tversky:      ["トヴェルスキー", "Amos Tversky", [], 1979],
  wendt:        ["アレクサンダー・ウェント", "Alexander Wendt", ["ウェント"], 1992],
  sikkink:      ["キャサリン・シッキンク", "Kathryn Sikkink", ["シッキンク"], 1998],
  keck:         ["マーガレット・ケック", "Margaret E. Keck", ["ケック"], 1998],
  ropp:         ["スティーヴン・ロップ", "Stephen C. Ropp", [], 1999],
  schimmelfennig:["シンマルフェニッヒ", "Frank Schimmelfennig", [], 2001],
  wiener:       ["アンティェ・ウィーナー", "Antje Wiener", [], null, "刊行年の記載なし"],
  price:        ["リチャード・プライス", "Richard Price", [], 1998],
  bachrachbaratz:["バクラック＆バラッツ", "Bachrach & Baratz", [], 1962, "DB本文は「バラッツ＆バラッツ」と誤記"],
  collier:      ["ポール・コリア", "Paul Collier", [], 2004],
  hoeffler:     ["アンケ・ホーフラー", "Anke Hoeffler", [], 2004],
  stewart:      ["フランセス・スチュワート", "Frances Stewart", [], 2008],
  fearon:       ["ジェームズ・フィアロン", "James D. Fearon", [], 2004],
  luttwak:      ["エドワード・ルトワック", "Edward N. Luttwak", [], 1999],
  cashore:      ["ベンジャミン・キャショーア", "Benjamin Cashore", [], null, "刊行年の記載なし"],
  // 9/8にユーザーが追加した語のための人物
  moravcsik:    ["モラフチック", "Andrew Moravcsik", [], 1993],
  ehaas:        ["エルンスト・ハース", "Ernst B. Haas", [], 1958],
  lindberg:     ["リンドバーグ", "Leon N. Lindberg", [], 1963],
  mogami:       ["最上敏樹", "", [], 2016],
  jacoby:       ["ジャコビー", "Wade Jacoby", [], 2010],
  victor:       ["ヴィクター", "David G. Victor", [], 2011],
  stevens:      ["スティーヴンス", "Casey Stevens", [], 2011],
  snyder:       ["リチャード・スナイダー", "Richard C. Snyder", [], 1962],
  goldstein:    ["ゴールドスタイン", "Judith Goldstein", [], 1993],
  watanabe:     ["渡邉智明", "", [], 2021],
  yukawa:       ["湯川拓", "", [], 2011],
  sabel:        ["セイベル", "Charles F. Sabel", [], 2012],
  zeitlin:      ["ツァイトリン", "Jonathan Zeitlin", [], 2012],
  nicolaidis:   ["ニコライディス", "Kalypso Nicolaïdis", [], 2006],
  hettne:       ["ヘトネ", "Björn Hettne", [], 1998],
  soderbaum:    ["セーデルバウム", "Fredrik Söderbaum", [], 1998],
  hoshino:      ["星野俊也", "", [], 2001],
};

// 機関・文書の追加はなし
const I = {};

// 用語名 → 提唱者[（id か [id, 役割]）]。none:true は「提唱者を特定しない語」
const T = {
  // ── リアリズム系
  "ネオリアリズム（構造的リアリズム）": { p: ["waltz", ["morgenthau", "関連"]], src: ["国際政治理論"] },
  "安全保障のジレンマ": { p: ["herz", ["jervis", "代表"]], src: ["国際政治理論"] },
  "脅威均衡論（balance of threat）": { p: ["walt"], src: ["国際政治理論"] },
  "バランシングとバンドワゴニング（内的均衡・外的均衡）": { p: ["waltz", ["schweller", "代表"]], src: ["国際政治理論"] },
  "覇権安定論": { p: ["kindleberger", "gilpin", ["keohane", "関連"]], src: ["国際政治理論"] },
  "パワートランジション論": { p: ["organski"], src: ["国際政治理論"] },
  "長期サイクル論（コンドラチェフ波動・モデルスキー）": { p: ["kondratiev", "modelski"], src: ["国際政治理論"] },
  "ネオクラシカル・リアリズム": { p: ["rose"], src: ["国際政治理論"] },
  // ── リベラリズム系
  "永遠平和論（カント）": { p: ["kant"], src: ["国際政治理論"] },
  "理想主義とユートピアニズム批判（第一次大論争）": { p: ["carr"], src: ["国際政治理論"] },
  "通商的リベラリズム": { p: [], none: true, src: ["国際政治理論"] },
  "相互依存の武器化": { p: ["farrell", "newman", ["keohane", "関連"], ["nye", "関連"]], src: ["国際政治理論"] },
  "絶対利得と相対利得": { p: [["grieco", "代表"], ["keohane", "代表"]], src: ["国際政治理論"] },
  "交流主義論と安全保障共同体": { p: ["deutsch"], src: ["国際政治理論"] },
  "民主的平和論": { p: [["doyle", "代表"], ["kant", "関連"]], src: ["国際政治理論"] },
  "ネオネオ統合（Neo-Neo Synthesis）": { p: [["dbaldwin", "整理"]], none: true, src: ["国際政治理論"] },
  "国際リベラル秩序（LIO）とその動揺": { p: [["ikenberry", "代表"]], src: ["国際政治理論"] },
  // ── 外交政策決定
  "合理的行為者モデル（アリソン第一モデル）": { p: ["allison"], src: ["国際政治理論"] },
  "組織過程モデル（アリソン第二モデル）": { p: ["allison"], src: ["国際政治理論"] },
  "官僚政治モデル（アリソン第三モデル）": { p: ["allison"], src: ["国際政治理論"] },
  "インクリメンタリズム（漸進主義）": { p: ["lindblom", ["simon", "関連"]], src: ["国際政治理論"] },
  "限定合理性とサティスファイシング": { p: ["simon"], src: ["国際政治理論"] },
  "認識過程モデル（シグナルとノイズ）": { p: ["wohlstetter", ["jervis", "代表"]], src: ["国際政治理論"] },
  "グループ思考シンドロームと悪魔の提言者": { p: ["janis"], src: ["国際政治理論"] },
  "プロスペクト理論（損失回避・参照基準点）": { p: ["kahneman", "tversky"], src: ["国際政治理論"] },
  // ── コンストラクティビズム系
  "弱いコンストラクティヴィズムと強いコンストラクティヴィズム": { p: [["phaas", "代表"], ["wendt", "代表"]], src: ["国際政治理論"] },
  "アナーキーの文化（Anarchy is what states make of it）": { p: ["wendt"], src: ["国際政治理論"] },
  "第三論争（合理主義 vs 構成主義）": { p: [["wendt", "関連"]], none: true, src: ["国際政治理論"] },
  "規範のライフサイクルと転換点": { p: ["finnemore", "sikkink"], src: ["国際政治理論"] },
  "規範起業家とフレーミング": { p: ["finnemore", "sikkink"], src: ["国際政治理論"] },
  "規制的効果と構成的効果": { p: [["finnemore", "関連"], ["sikkink", "関連"], ["wendt", "関連"]], none: true, src: ["国際政治理論"] },
  "スパイラル・モデル": { p: ["risse", "ropp", "sikkink"], src: ["国際政治理論"] },
  "ブーメラン・パターン": { p: ["keck", "sikkink"], src: ["国際政治理論"] },
  "言説の拘束（rhetorical entrapment）": { p: [["schimmelfennig", "代表"]], src: ["国際政治理論"] },
  "逆螺旋（backlash）と規範の後退": { p: [["wiener", "関連"]], none: true, src: ["国際政治理論"] },
  "規範の接ぎ木（grafting）とゲートキーパー": { p: [["price", "代表"], ["bachrachbaratz", "関連"]], src: ["国際政治理論"] },
  // ── 紛争・民間レジーム
  "資源の呪い仮説": { p: [["collier", "代表"], ["hoeffler", "代表"]], src: ["国際政治理論"] },
  "水平的不平等（集団間格差）仮説": { p: [["stewart", "代表"]], src: ["国際政治理論"] },
  "内戦の長期化要因": { p: [["fearon", "代表"], ["kaldor", "関連"], ["luttwak", "関連"]], src: ["国際政治理論"] },
  "対抗レジームとグリーンウォッシュ": { p: [["cashore", "関連"]], none: true, src: ["国際政治理論"] },
  // ── 理論の作法・方法論
  "中範囲理論とパーシモニーの原則": { p: [["merton", "関連"], ["waltz", "関連"]], none: true, src: ["国際政治理論"] },
  "因果推論の三要件と擬似相関": { p: [], none: true, src: ["国際政治理論"] },
  "反証可能性（ポパー）": { p: ["popper", ["waltz", "関連"]], src: ["国際政治理論"] },
  "プロセス・トレーシング": { p: [], none: true, src: ["国際政治理論"] },
  "選択バイアス（逆因果）とPKO効果の検証": { p: [], none: true, src: ["国際政治理論"] },
  // ── 9/8にユーザーが追加した語
  "リベラル政府間主義（liberal intergovernmentalism）": { p: ["moravcsik"], src: ["第2章"] },
  "新機能主義（neofunctionalism）": { p: ["ehaas", ["lindberg", "代表"], ["watanabe", "整理"]], src: ["第2章"] },
  "普遍的国際機構と地域機構の機能的分業（補完・代替／地域調整／コスト配分）": { p: [["watanabe", "整理"], ["mogami", "関連"], ["jacoby", "関連"], ["meunier", "関連"]], src: ["第2章"] },
  "ガバナンスの垂直的変化・水平的変化": { p: [["yamada", "整理"], ["keohane", "関連"], ["victor", "関連"]], src: ["第3章"] },
  "利用可能な知識（usable knowledge）と知識の3要件": { p: ["phaas", ["stevens", "代表"]], src: ["第3章"] },
  "専門家組織の政治的独立性（専門家登録簿方式／開かれたメンバーシップ）": { p: ["phaas", "stevens"], src: ["第3章"] },
  "状況規定（definition of the situation）と理念の因果的役割": { p: ["snyder", ["goldstein", "代表"], ["keohane", "代表"]], src: ["第3章"] },
  "社会的学習（social learning）": { p: ["phaas", ["ehaas", "関連"]], src: ["第3章"] },
  "科学・政策インターフェイス（science-policy interface）": { p: [["young", "関連"], ["yamada", "整理"]], none: true, src: ["第3章"] },
  "規範間対立の調整メカニズム（内政不干渉 vs 人権）と規範の一貫性": { p: [["watanabe", "整理"], ["yukawa", "関連"], ["manners", "関連"], ["nishitani", "関連"]], src: ["第2章"] },
  "地域機構の3つのイメージ（利益集合体／GGの担い手／規範エージェント）": { p: [["watanabe", "提唱"], ["hoshino", "関連"], ["mogami", "関連"], ["yamada", "関連"]], src: ["第2章"] },
  "実験主義的ガバナンス（experimentalist governance）": { p: ["sabel", "zeitlin"], src: ["第2章"] },
  "市場パワー・通商を通じたパワー（power through trade）": { p: ["meunier", "nicolaidis"], src: ["第2章"] },
  "新しいリージョナリズム（new regionalism）": { p: ["hettne", "soderbaum"], src: ["第2章"] },
  "標準作業手続き（SOP）と国益の漸進的変化": { p: ["allison", ["phaas", "関連"]], src: ["第3章"] },
};

module.exports = { P, I, T };
